autostart.sh &

sleep 2

# === dwm section ===
# setup for dwm log
# [ -d ~/.config/dwm ] || mkdir -p ${XDG_CACHE_HOME}/dwm

# restart dwm by Super + Shift + q instead of quitting it
# while true; do
#     dwm 2> ${XDG_CACHE_HOME}/dwm/dwm.log
# done

# quit dwm by Super + Shift + q
# exec dwm


# === i3 section ===
exec i3

# === xmonad section ===
# exec xmonad


# === awm section ===
# source /home/me/homework/pz/A-Window-Manager/venv/bin/activate
# exec python /home/me/homework/pz/A-Window-Manager/wm.py > "awm.log"
