autostart.sh &

# setup for dwm log
[ -d ~/.config/dwm ] || mkdir -p ${XDG_CACHE_HOME}/dwm

# restart dwm by Super + Shift + q instead of quitting it
while true ; do
    dbus-launch dwm 2>&1 > ${XDG_CACHE_HOME}/dwm/dwm.log    
done

# quit dwm by Super + Shift + q
# exec dwm
